@startuml
'https://plantuml.com/class-diagram
package java{
package app{
class Main{}

package config{
class ThymeleafConfig{
+templateEngine()
}
}

package controllers{
class OrderController{
+static void addRoutes(Javalin app, ConnectionPool connectionPool)
-static void addOrder()
-static void showOrder()
-static void index(Context ctx,ConnectionPool connectionPool)

}
class UserController{
+static void AddRoutes(Javalin app, ConnectionPool connectionPool)
-static void createuser(Context ctx, ConnectionPool connectionPool)
-static void logout(Context ctx)
+static void login(Context ctx, ConnectionPool connectionPool)
}

}

package entities{
class Bottoms{
-int bottomsID
-String bottoms
-float price
+int getBottomsID()
+String getBottoms()
+Float getPrice()}
class Toppings{
-int toppingID
-String toppings
-float price
+int getToppingID()
+String getToppings()
+Float getPrice()}
class User{
-int userID
-String userName
-String password
-String role
-float balance
+int getUserID()
+String getUserName()
+String getPassword()
+String getRole()
+float getBalance()
+float addToBalance()
+float setBalance()
}
}

package exceptions{
class DatabaseException{}
}

package persistence{
class ConnectionPool{
-ConnectionPool()
+getInstance(String user, String password, String URL, String db)
+getConnection()
-createHikrariConnectionPool()
}
class UserMapper{
+static User login(String userName, String password, ConnectionPool connectionPool)
+static void createuser(String userName, String password, ConnectionPool connectionPool)
}
class OrderItemMapper{
+static getBottomsAndToppings
}
class OrderMapper{
+static getOrdersPerUser()
+static getAllOrders()
}
}
}
}

package resources{
package public{
package css{
object style
}
package images{}
}
package sql{
}
package templates{
object index

}
}
}

@enduml